site_name: Shift Left Utilities v0.1.44
repo_url: https://github.com/jbcodeforce/shift_left_utils
site_url: https://jeromeboyer.net/shift_left_utils
copyright: Copyright &copy; 2024 Jerome Boyer
nav:
  - Introduction: index.md
  - User Guide:
    - Environment Setup: setup.md
    - Recipes: recipes.md
    - CLI References: command.md
    - Test Harness: coding/test_harness.md
    - Pipeline Management: pipeline_mgr.md
    - Blue/Green Deployment: blue_green_deploy.md
    - Performance Testing: perf_test.md
    - MCP server: mcp/index.md
    - Flink SQL best practices: https://jbcodeforce.github.io/flink-studies/coding/flink-sql/
  - Tutorials:
    - Introduction: tutorial/index.md
    - Setup Lab: tutorial/setup_lab.md
    - Migration AI Lab: tutorial/migration_ai_lab.md
    - Date Engineer day to day work - Lab: tutorial/de_lab.md
    - SRE CI/CD process and other tasks - Lab: tutorial/sre_lab.md
  - For Contributors:
      - Contributing: contributing.md
      - Code structure: coding/index.md
      - AI based migration: coding/llm_based_translation.md
      - Feature Tracking: tracking.md
theme:
  name: material
  logo: assets/batchy.png
  favicon: assets/batchy.png
  palette:
    scheme: default
  language: en
  features:
      - content.code.annotate
      - content.code.copy
      - content.tooltips
      - content.tabs.link
      - search.suggest
      - search.highlight
      - navigation.instant
      - navigation.instant.progress
      #- navigation.tabs
      - navigation.tabs.sticky
      - navigation.tracking
      - navigation.sections
      - navigation.expand
      - navigation.top
      - navigation.footer

extra_css: ["extra.css"]
plugins:
  - search:
      lang: en
  - minify:
      minify_html: true
  - mkdocstrings
  - table-reader

markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - admonition
  - codehilite
  - footnotes
  - tables
  #- pymdownx.blocks.caption
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.smartsymbols
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github
      link: 'https://github.com/jbcodeforce'
    - icon: fontawesome/brands/linkedin
      link: 'https://linkedin.com/in/jeromeboyer'
    - icon: fontawesome/solid/paper-plane
      mailto: jerome@intelligent-automations.com
